### PR TITLE
Autofix precommit for PRs

### PR DESCRIPTION
**Pull request by ProKil**
Using autofix.ci to automatically fix pre commit errors. It would fix it and push the fixed version as demoed below.
 

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed
- [x] Branch name follows `type/descript` (e.g. `feature/add-llm-agents`)
- [x] Ready for code review

### CODE REVIEW

**Comment by XuhuiZhou** [comment]
qq, why we need this? I thought the GitHub actions could ensure the code merged to the main follows the format. Is this more like helping people code more efficiently?

**Review by XuhuiZhou — COMMENTED** [review]
left a clarification question

**Comment by ProKil** [comment]
Yes, this is just for people who are not familiar with pre-commit to save time for contributors. Inspired by #133

**Review by XuhuiZhou — APPROVED** [review]
cool;!

**Pull request merged**
