### PR TITLE
Update server.py

### PR DESCRIPTION
**Pull request by Armxyz1**
Closes # 

## 📑 Description

A small spelling change from simutaneous to simultaneous, in server.py.

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed
- [ ] Branch name follows `type/descript` (e.g. `feature/add-llm-agents`)
- [x] Ready for code review

### CODE REVIEW

**Comment by ProKil** [comment]
Thanks @Armxyz1 !

**Review by ProKil — APPROVED** [review]

**Comment by ProKil** [comment]
Hi @Armxyz1 Thanks for you contribution! Sorry the github workflow was not set up right, so the CI check didn't run properly. Would you mind merging [ci/ci-pr-trigger](https://github.com/sotopia-lab/sotopia/tree/ci/ci-pr-trigger) into your PR? Or alternatively we can wait until #96 is merged and then merge main into your PR.

**Comment by Armxyz1** [comment]
> Hi @Armxyz1 Thanks for you contribution! Sorry the github workflow was not set up right, so the CI check didn't run properly. Would you mind merging [ci/ci-pr-trigger](https://github.com/sotopia-lab/sotopia/tree/ci/ci-pr-trigger) into your PR? Or alternatively we can wait until #96 is merged and then merge main into your PR.

Should be done now. Please verify.

**Comment by ProKil** [comment]
Thanks!

Would you mind changing parallel.py as well? There are four "simutaneous"es https://github.com/Armxyz1/sotopia/blob/434bf5425d7081912f4b6b57abb9b2312ad84324/sotopia/envs/parallel.py#L130

**Comment by Armxyz1** [comment]
> Thanks!
> 
> Would you mind changing parallel.py as well? There are four "simutaneous"es https://github.com/Armxyz1/sotopia/blob/434bf5425d7081912f4b6b57abb9b2312ad84324/sotopia/envs/parallel.py#L130

Done! But it's still failing the checks somehow

**Pull request merged**
