### PR TITLE
Remove `all_pks` from Sampler.sample

### LINKED ISSUE #159: [FEAT]: Remove all_pks from UniformSampler
### Description

https://github.com/sotopia-lab/sotopia/blob/be6c333c8ffeb8e370fead8abddc676f85e54656/sotopia/samplers/uniform_sampler.py#L55

is the only place we use `all_pks`, which could be slow when the number of keys is large since it is using `scan_its` which sends a request to the database for each key. 

We can replace it with keys + random choice. 

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ProKil**
Closes #159  

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed
- [x] Branch name follows `type/descript` (e.g. `feature/add-llm-agents`)
- [x] Ready for code review

### CODE REVIEW

**Comment by ProKil** [comment]
@XuhuiZhou Would you mind helping me check if this is faster? I have other optimization in mind, but I want to confirm that this works. It should be much faster when calling sample function

**Review by XuhuiZhou — COMMENTED** [review]
@ProKil  I tried and timed the 
` python examples/minimalist_demo.py` on this new version of code, and it costs me 4mins to finish a single episode.

Any chance you may test on your side and we can compare?

Specifically,

```
time python examples/minimalist_demo.py
```
And the output is:

```
python examples/minimalist_demo.py  1.86s user 2.64s system 1% cpu 4:06.94 total
```

**Comment by XuhuiZhou** [comment]
New timing after running, much faster!
`python examples/minimalist_demo.py  1.73s user 2.33s system 6% cpu 59.443 total`

**Comment by ProKil** [comment]
@XuhuiZhou Should we merge it then?

**Review by XuhuiZhou — APPROVED** [review]

**Pull request merged**
