### PR TITLE
remove double initialization behavior

### PR DESCRIPTION
**Pull request by XuhuiZhou**
Closes # 

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed
- [ ] Branch name follows `type/descript` (e.g. `feature/add-llm-agents`)
- [ ] Ready for code review

### CODE REVIEW

**Comment by ProKil** [comment]
This would break the RedisAgent initialization. In our previous implementation, RedisAgent will be first initialized as an LLMAgent and reinitialized as RedisAgent, which is not ideal. After you delete the reinitialization snippet, this is broken. 

Please change this `get_agent_class` accordingly.

**Comment by XuhuiZhou** [comment]
> This would break the RedisAgent initialization. In our previous implementation, RedisAgent will be first initialized as an LLMAgent and reinitialized as RedisAgent, which is not ideal. After you delete the reinitialization snippet, this is broken.
> 
> Please change this `get_agent_class` accordingly.

@ProKil can you point out to me which line of code is causing the error?

**Comment by ProKil** [comment]
https://github.com/sotopia-lab/sotopia/blob/1cde9ec7e1785cbdb471b2ebef65300e9d8f78a0/sotopia/server.py#L258

RedisAgent is not dealt with here.

**Comment by XuhuiZhou** [comment]
Has been addressed

**Pull request closed without merging**
