### PR TITLE
Tutorial notebooks that can be directly opened in colab

### LINKED ISSUE #91: [BUG]: Tuturial failed?
### Description of the bug

image

### Steps To Reproduce

1. go to [1.2 Browsing sotopia data](https://colab.research.google.com/drive/1Gi2U3cA0KG1nekw1A0N0DZpx6gKrj8Nc?usp=sharing)

2. run all

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ProKil**
A follow-up to #73. This brings version control to the notebook tutorials.

Reviewers: none of the links could be opened as-is before merging into main. You can change `main`
 in the links to `doc/colab-notebook-files` in order to view the links. 
## 📑 Description
Added two jupyter notebooks under `notebooks/tutorials`.
Updated link in the readme.
Minor update of the sotopia logo. 

Also closes #91.

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed
- [x] Branch name follows `type/descript` (e.g. `feature/add-llm-agents`)
- [x] Ready for code review

### CODE REVIEW

**Comment by lwaekfjlk** [comment]
just curious what is the meaning of this icon

**Comment by ProKil** [comment]
> just curious what is the meaning of this icon

Lol, it is inspired by the chatting interface: the black semi- and quarter circles are chat bubbles. And you can see a white S in the middle.

**Comment by ProKil** [comment]
@lwaekfjlk @XuhuiZhou feel free to leave more feedback on this. More content? Better interface? Thank you!

**Review by XuhuiZhou — APPROVED** [review]

**Comment by ProKil** [comment]
Thanks @XuhuiZhou

**Comment by XuhuiZhou** [comment]
@ProKil Sorry I accidentally merged it lolll

I indeed has one small comment:

For the markdown here, any chance you can link to the sotopia docs that include instructions for different platforms?

`Download Redis: This code block is exactly the same as`


I guess for this instruction here, for Mac users, people are wondering if they can stop the server and restart with the previously saved data. (since they are usually using their personal laptop)
image

**Comment by lwaekfjlk** [comment]
Thanks @ProKil for the contribution and thanks @XuhuiZhou for the comments, looks good to me.

**Pull request merged**
