### PR TITLE
update pyproject.toml

### LINKED ISSUE #49: [BUG]: missing langchain_community in the config
### Description of the bug

langchain_community is imported in the generation_utils/generation.py but not mentioned in the poetry.

### Steps To Reproduce

Check generation_utils/generation.py 

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by lwaekfjlk**
Closes #49 

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed
- [x] Branch name follows `type/descript` (e.g. `feature/add-llm-agents`)
- [x] Ready for code review

### CODE REVIEW

**Comment by ProKil** [comment]
@lwaekfjlk are you still working on this PR?

**Comment by lwaekfjlk** [comment]
@ProKil ， yeah, it looks like the current error is caused by openai calling?

**Comment by ProKil** [comment]
It is because of the change of langchain API

**Comment by lwaekfjlk** [comment]
Looks like the langchain version should be hard coded as 0.1.5, utilizing ^0.1.5 will activate it to install 0.1.17 which cannot pass the mypy testing.

**Review by ProKil — APPROVED** [review]

**Pull request merged**
