### PR TITLE
Adding a doc site using Nextra

### LINKED ISSUE #75: Sotopia doc site.

### PR DESCRIPTION
**Pull request by ProKil**
Closes #75   

This is deployed onto https://docs.sotopia.world!

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed
- [x] Branch name follows `type/descript` (e.g. `feature/add-llm-agents`)
- [x] Ready for code review

### CODE REVIEW

**Comment by lwaekfjlk** [comment]
Looks like https://dev.sotopia.world/ is not reachable?

**Comment by ProKil** [comment]
sorry my bad. https://docs.sotopia.world

**Comment by ProKil** [comment]
@lwaekfjlk @XuhuiZhou This PR aims at adding the doc site. Please review and merge and we can work on #76 and #77

**Review by lwaekfjlk — COMMENTED** [review]
feel a little bit weird when opening the link and only see on image. Should we put part of the Q&A at the home?

**Comment by ProKil** [comment]
OK I will change the index.mdx

**Comment by ProKil** [comment]
@lwaekfjlk Check out docs.sotopia.world

**Comment by lwaekfjlk** [comment]
yes, checked. looks good.

**Pull request merged**
