### PR TITLE
fix empty background issue

### LINKED ISSUE #24: [BUG]: potential buggy behavior in script background
### Description of the bug

The current setting of the `ScriptBackground` has the `to_natural_language` function that would wipe off the agents' background when either of agent's background is blank. This would reduce all the sotopia situation with "stranger" relationship to sotopia-lite

@bugsz Can you double check this and see if we need to fix this problem?

### Steps To Reproduce

see the `ScriptBackground` class or run mutual friends scenarios.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by bugsz**
Closes #24 

## 📑 Description

Since in `stranger` relations the other's background is not visible, using `and` will wipe out all backgrounds. So we use `or` instead.
@XuhuiZhou Here is the fix. I will run experiments later and we can merge after it behaves correctly

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed
- [ ] Branch name follows `type/descript` (e.g. `feature/add-llm-agents`)
- [ ] Ready for code review

### CODE REVIEW

**Comment by bugsz** [comment]
I think there are some conflicts with previous expectations?
In `text_xml_renderer.py` it seems that we are expecting backgrounds to be empty. Maybe we should also change that?
@ProKil @XuhuiZhou What do you think?

**Comment by ProKil** [comment]
@bugsz Thanks for your contribution. Can you describe the test case and what your expected outputs are?

**Comment by bugsz** [comment]
I think what Xuhui wants is to make the speaker background visible while the listener invisible? 
For example, in the test cases above, in which john and jane are strangers, we might want the following output
```
obs["John"].last_turn == "Here is the context of this interaction:\n" 
     "Scenario: test\n"
     "Participants: John and Jane\n" 
     "John's background: this is a background"
     "Jane's background: unknown"
     "John's goal: agent_1's goal\n" 
     "Jane's goal: Unknown"
```

**Comment by ProKil** [comment]
@bugsz that makes sense. Would you mind updating that test case and reply me with a link to it?

**Comment by bugsz** [comment]
@ProKil Here is the updated test case.
https://github.com/sotopia-lab/sotopia/blob/fd6700a889548b003b316857fff60f1d6e4577f7/tests/renderers/test_xml_renderer.py#L64-L99

**Review by ProKil — APPROVED** [review]

**Pull request merged**
