### PR TITLE
support env+social_goal gen pipeline on redis

### LINKED ISSUE #5: [FEAT]: Support an example of constructing own dataset on your own redis database
### Description

Should provide the overall pipeline for generating the data from scratch.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by lwaekfjlk**
Closes #5  

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed
- [ ] Branch name follows `type/descript` (e.g. `feature/add-llm-agents`)
- [ ] Ready for code review

### CODE REVIEW

**Comment by ProKil** [comment]
@lwaekfjlk Can you merge main into this branch to see if the checks will automatically run?

**Comment by lwaekfjlk** [comment]
@ProKil yes, I will do that later today, thanks for reminding

**Comment by lwaekfjlk** [comment]
sotopia-llm repo provides a much better version for that now.

**Comment by ProKil** [comment]
Feel free to merge that part into this repo as well!

**Pull request closed without merging**
