### PR TITLE
Langchain V0.2 and Sync API deprecated

### LINKED ISSUE #21: [BUG]: Reward prompt log is wrong due to the use of shared instance member across different coroutines
### Description of the bug

This line stores the reward prompt from the instance member -- `evaluator.prompt` which is updated in each `__acall__`. This is a dangerous operation since the prompt is lost after several parallel call to `env.astep`. 

https://github.com/sotopia-lab/sotopia/blame/c4fdb166bab6f20ee541c48dd614981d38303b19/sotopia/envs/parallel.py#L564

### Steps To Reproduce

In the current codebase shared in #7, you can find that in 66% of the reward prompts neither of the character names is mentioned. 

@sharonwx54 contributed this script to reproduce:

```python
import sys
import os
import json
from sotopia.database.persistent_profile import AgentProfile, EnvironmentProfile, RelationshipProfile
from sotopia.database.logs import EpisodeLog
from sotopia.database.env_agent_combo_storage import EnvAgentComboStorage
import pandas as pd

SELECTED_TAG = ['gpt-4_gpt-3.5-turbo_v0.0.1_clean', 'gpt-4_gpt-4_v0.0.1_clean']
selected_episodes = {}
for tag in SELECTED_TAG:
    tag_epis = EpisodeLog.find(EpisodeLog.tag == tag).all()
    if len(tag_epis) > 0:
        selected_episodes[tag]=tag_epis
concat_epilist = sum(selected_episodes.values(), [])

def check_msg_prompt_align(episode):
    party1 = episode.messages[0][0][1]
    party2 = episode.messages[0][1][1]
    if party1 and party2 not in episode.rewards_prompt:
        print(episode.pk)
    return

for episode in concat_epilist:
    check_msg_prompt_align(episode)
```

### Additional Information

We can either

1. drop the reward prompts
2. find a coroutine-safe way to log them

### PR DESCRIPTION
**Pull request by ProKil**
## 📑 Description

This PR does several things:

1. Upgrade langchain to the latest v0.2 version;
2. Remove litelllm completely;
3. Remove sync apis (long overdue, and finally got done): remove every generate*(), raise exceptions in agent.act()
4. Remove prompt return. Closes #21 

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed
- [x] Branch name follows `type/descript` (e.g. `feature/add-llm-agents`)
- [x] Ready for code review

This change will be reflected in the new version of documentation.

### CODE REVIEW

**Review by lwaekfjlk — COMMENTED** [review]
Any reason to deprecate sync API? I think if we want to build simple demo based on sotopia, sync API is easier to use for initial testing? Probably we should keep the sync API in the code for future use but not using them?

**Comment by ProKil** [comment]
It is hard to maintain two versions of the same functions side-by-side. Are there specific use of sync functions that you are thinking about?

Since most of sync apis are **pure** function (i.e. no side effects), we could easily execute them in a process/thread executor in a sync context. Do you need some documentation or examples?

**Comment by ProKil** [comment]
Normally I would separate this into two PRs: one for upgrading langchain, and another for removing sync apis. But I found that there are some weird mypy errors only exist for the sync apis after upgrading langchain. So I think it might make sense to just use this PR to solve these two problems together.

**Comment by ProKil** [comment]
@lwaekfjlk I could re-implement all of the sync apis as wrappers of the corresponding async ones, but do you think it is helpful to provide that in the sotopia package?

**Comment by lwaekfjlk** [comment]
Got your point. I just think that considering the difficulty of using sotopia package, probably we need to provide a sync api wrapped out of the async ones. Otherwise, imagine you are a beginner of using sotopia package and what to do some intial test, you would find there is no simple sync API (which you normally use for OpenAI or other things) but only those async ones that a beginner might not be familiar with. 

That can be kind of confusing.

**Comment by ProKil** [comment]
Cool! Would you mind adding some use cases?

**Comment by lwaekfjlk** [comment]
where would be a good place to add? The notebook demo?

**Comment by ProKil** [comment]
You can add a failed test case

**Comment by lwaekfjlk** [comment]
sure, I will do that after work.

**Comment by ProKil** [comment]
> sure, I will do that after work.

Thank you so much! :) 🤝

**Comment by ProKil** [comment]
@lwaekfjlk Just added a helper function `async_to_sync` which can convert any async function to a sync one with type safety.

**Comment by lwaekfjlk** [comment]
cool, looks good

**Review by lwaekfjlk — APPROVED** [review]

**Pull request merged**
