### PR TITLE
support codecov

### LINKED ISSUE #81: [FEAT]: support tesing coverage statistics
### Description

We can add testing coverage for the repo.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by lwaekfjlk**
Closes #81  

## 📑 Description

More setting related to CodeCov ( https://app.codecov.io/ ) needs to be done on repo author's side. @ProKil

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed
- [x] Branch name follows `type/descript` (e.g. `feature/add-llm-agents`)
- [x] Ready for code review

### CODE REVIEW

**Comment by ProKil** [comment]
hi @lwaekfjlk I have added a `CODECOV_TOKEN` to the secrets, and codecov asks me to add a new github action:

```yaml
- name: Upload coverage reports to Codecov
  uses: codecov/codecov-action@v4.0.1
  with:
    token: ${{ secrets.CODECOV_TOKEN }}
```

Could you help with adding this github action?

**Comment by lwaekfjlk** [comment]
ok, will do later.

**Comment by lwaekfjlk** [comment]
@ProKil Please check the codecov report.

**Comment by ProKil** [comment]
Thanks! Would this be displayed on the readme.md?

**Comment by lwaekfjlk** [comment]
for badge, should look something like this:

  <a href="https://codecov.io/github/opendevin/opendevin?branch=main">CodeCov</a>

**Review by ProKil — APPROVED** [review]

**Pull request merged**
