### PR TITLE
add agreement calculation for human eval

### PR DESCRIPTION
**Pull request by lwaekfjlk**
Closes # 

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed
- [x] Branch name follows `type/descript` (e.g. `feature/add-llm-agents`)
- [x] Ready for code review

### CODE REVIEW

**Comment by lwaekfjlk** [comment]
This file is originally proposed by Xuhui but I found that it is deleted from the latest branch.

**Comment by XuhuiZhou** [comment]
Hi @lwaekfjlk! Thanks for making the pull request, any chance you may add a readme doc and fix the mypy error?

**Comment by lwaekfjlk** [comment]
sure, will do later.

**Comment by lwaekfjlk** [comment]
Hi @XuhuiZhou , I fix the mypy error and update the readme file. Can you help merge this PR?

**Review by XuhuiZhou — APPROVED** [review]

**Pull request merged**
